name: Build and deploy jupyter book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build jupyter book
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda env create -f environment.yml
          conda activate now
          pip install -r requirements.txt
          make
          cd jupyter-book
          pip install -r requirements.txt
          make clean
          make
          conda deactivate
      - name: Deploy jupyter book in webserver
          ls ./
          scp -r jupyter-book/_build/html/* aramislab.paris.inria.fr:~/workshops/NOW/2023/
