name: Build and deploy jupyter book

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/miniconda3/envs/now
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Update environment
        run: conda env update -n now -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build jupyter book
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate now
          pip install -r requirements.txt
          make
          cd jupyter-book
          pip install -r requirements.txt
          make clean
          make
          sed -i 's+github/aramis-lab/NOW-2023/blob/main/jupyter-book/notebooks+github/aramis-lab/NOW-2023/blob/main/notebooks+g' _build/html/notebooks/*.html
          conda deactivate
      - name: Deploy jupyter book in webserver
        run: |  
          ls ./
          scp -r jupyter-book/_build/html/* aramislab:/srv/local/workshops/NOW/2023/
